[package]
authors = ["Jerónimo Sánchez <jeronimosg@hotmail.es>"]
edition = "2018"
name    = "safe_ipc"
version = "0.1.0"

[dependencies]
cfg-if = "0.1.10"
rand   = "0.7.3"

[target.'cfg(unix)'.dependencies]
nix = "0.18.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [
    "ntdef",
    "winerror",
    "errhandlingapi",
    "handleapi",
    "memoryapi",
    "winbase",
    "winnt",
    "securitybaseapi",
] }
